[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run preview"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"

[variables]
NIXPACKS_NODE_VERSION = "20"