[build]
builder = "nixpacks"

[deploy]
startCommand = "python -c 'from app import init_app; init_app()' && gunicorn --bind 0.0.0.0:$PORT --worker-class gevent --worker-connections 1000 --timeout 0 app:app"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"